service: websiteovertime #name this whatever you want

provider:
 name: aws
 runtime: python3.10
 region: us-east-1
 memorySize: 128
plugins:
  - serverless-wsgi
  - serverless-python-requirements
custom:
 wsgi:
   app: app_lambda.app
   packRequirements: true
functions:
 app:
   handler: wsgi_handler.handler
   events:
     - http: ANY /
     #- http: 'ANY'